package com.mgtech.domain.entity.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mgtech.domain.entity.database.ReminderEntity;

import com.mgtech.domain.entity.database.ReminderEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reminderEntityDaoConfig;

    private final ReminderEntityDao reminderEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reminderEntityDaoConfig = daoConfigMap.get(ReminderEntityDao.class).clone();
        reminderEntityDaoConfig.initIdentityScope(type);

        reminderEntityDao = new ReminderEntityDao(reminderEntityDaoConfig, this);

        registerDao(ReminderEntity.class, reminderEntityDao);
    }
    
    public void clear() {
        reminderEntityDaoConfig.getIdentityScope().clear();
    }

    public ReminderEntityDao getReminderEntityDao() {
        return reminderEntityDao;
    }

}
