package com.mgtech.domain.entity.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.format.DateFormat;

import com.mgtech.domain.utils.MyConstant;

/**
 * Entity mapped to table "REMINDER_ENTITY".
 */
public class ReminderEntity {

    private Long id;
    private java.util.Date startTime;
    private java.util.Date endTime;
    private String name;
    private String dosage;
    private long remindTime;
    private int hashCodeId;

    public ReminderEntity() {
    }

    public ReminderEntity(Long id) {
        this.id = id;
    }

    public ReminderEntity(Long id, java.util.Date startTime, java.util.Date endTime, String name, String dosage, long remindTime, int hashCodeId) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
        this.name = name;
        this.dosage = dosage;
        this.remindTime = remindTime;
        this.hashCodeId = hashCodeId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getStartTime() {
        return startTime;
    }

    public void setStartTime(java.util.Date startTime) {
        this.startTime = startTime;
    }

    public java.util.Date getEndTime() {
        return endTime;
    }

    public void setEndTime(java.util.Date endTime) {
        this.endTime = endTime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDosage() {
        return dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    public long getRemindTime() {
        return remindTime;
    }

    public void setRemindTime(long remindTime) {
        this.remindTime = remindTime;
    }

    public int getHashCodeId() {
        return hashCodeId;
    }

    public void setHashCodeId(int hashCodeId) {
        this.hashCodeId = hashCodeId;
    }


    @Override
    public String toString() {
        return "ReminderEntity{" +
                "id=" + id +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", name='" + name + '\'' +
                ", dosage='" + dosage + '\'' +
                ", remindTime=" + DateFormat.format(MyConstant.FULL_DATETIME_FORMAT,remindTime) +
                ", hashCodeId=" + hashCodeId +
                '}';
    }
}
